### ISSUE TITLE
Add prototool linter to build process

### ISSUE THREAD

**Issue by alpe** [iov-one/weave#302]
Note: please add to makefile, not just CI. eg.`make lint` and add needed tools to `make tools`

We can enforce protobuf best practices like snake_case by using [prototool](https://github.com/uber/prototool):
* How to use it:
```
prototool lint
cmd/bnsd/app/codec.proto:58:3:Enum field "USERNAME" is expected to have the prefix "NFT_TYPE_".
cmd/bnsd/app/codec.proto:58:3:Zero value enum field "USERNAME" is expected to have the name "NFT_TYPE_INVALID".
cmd/bnsd/app/codec.proto:59:3:Enum field "TICKER" is expected to have the prefix "NFT_TYPE_".
cmd/bnsd/app/codec.proto:60:3:Enum field "BLOCKCHAIN" is expected to have the prefix "NFT_TYPE_".
cmd/bnsd/app/codec.proto:61:3:Enum field "BOOTSTRAP_NODE" is expected to have the prefix "NFT_TYPE_".
```
* Config `prototool.yaml`
```
excludes:
  - ./vendor

protoc:
  # The Protobuf version to use from https://github.com/protocolbuffers/protobuf/releases.
  # By default use 3.6.1.
  # You probably want to set this to make your builds completely reproducible.
  version: 3.6.1

  # Additional paths to include with -I to protoc.
  # By default, the directory of the config file is included,
  # or the current directory if there is no config file.
  includes:
    - ./vendor
    - ../../..


  # If not set, compile will fail if there are unused imports.
  # Setting this will ignore unused imports.
  allow_unused_imports: false

lint:
  rules:
    remove:
      - FILE_OPTIONS_REQUIRE_JAVA_MULTIPLE_FILES
      - FILE_OPTIONS_REQUIRE_JAVA_OUTER_CLASSNAME
      - FILE_OPTIONS_REQUIRE_JAVA_PACKAGE
      - FILE_OPTIONS_REQUIRE_GO_PACKAGE
```
